# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi_App', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_Staffctive',
            new_name='is_staffactive',
        ),
    ]
